name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    name: Run C/C++ Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck

      - name: Run clang-tidy
        run: |
          find . -name '*.cpp' -o -name '*.c' -o -name '*.h' | xargs clang-tidy --quiet || true

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --quiet --std=c++11 --language=c++ --force . || true
